services:
    php-framework:
        container_name: php-framework-v2
        build: .
        volumes: 
             - ./app:/var/www/html
             - ./logs:/var/log/apache2/
        ports:
             - 8080:80
